--USUARIO
--ALTER TABLE USUARIO DROP CONSTRAINT FK_ID_ROL
--ALTER TABLE USUARIO DROP CONSTRAINT FK_ID_TIPO_DOC
ALTER TABLE USUARIO ADD CONSTRAINT FK_ID_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
ALTER TABLE USUARIO ADD CONSTRAINT FK_ID_TIPO_DOC FOREIGN KEY (ID_TIPO_DOC) REFERENCES TIPO_DOCUMENTO (ID_TIPO_DOC)

--PEDIDO
--ALTER TABLE PEDIDO DROP CONSTRAINT FK_ID_PRODUCTO
ALTER TABLE PEDIDO ADD CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)

--PRODUCTO
--ALTER TABLE PRODUCTO DROP CONSTRAINT FK_ID_CATEG
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_ID_CATEG FOREIGN KEY (ID_CATEG) REFERENCES CATEGORIA (ID_CATEG)

--VENTA
--ALTER TABLE VENTA DROP CONSTRAINT FK_ID_PEDIDO
ALTER TABLE VENTA ADD CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
