USE BD_Sistema_Ventas
GO 
DELETE FROM USUARIO
GO 
DELETE FROM TIPO_DOCUMENTO
GO
DELETE FROM ROL
GO
DELETE FROM VENTA
GO
DELETE FROM PEDIDO
GO
DELETE FROM PRODUCTO
GO
DELETE FROM CATEGORIA
GO



INSERT INTO ROL (ID_ROL,NOMBRE_ROL,SN_ACTIVO,FEC_CREACION) VALUES (1,'ADMINISTRADOR',-1,GETDATE())
INSERT INTO ROL (ID_ROL,NOMBRE_ROL,SN_ACTIVO,FEC_CREACION) VALUES (2,'CLIENTE',-1,GETDATE())
GO
SELECT* FROM ROL
GO
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOC,NOMBRE_TIPO_DOC,FEC_CREACION) VALUES (1,'CÉDULA DE CIUDADANÍA',GETDATE())
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOC,NOMBRE_TIPO_DOC,FEC_CREACION) VALUES (2,'TARJETA DE IDENTIDAD',GETDATE())
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOC,NOMBRE_TIPO_DOC,FEC_CREACION) VALUES (3,'CÉDULA DE EXTRANJERÍA ',GETDATE())
GO
SELECT * FROM TIPO_DOCUMENTO
GO
INSERT INTO USUARIO (USUARIO,NOMBRE,APELLIDO,CELULAR,DIRECCION,EMAIL,NRO_DOC,SN_ACTIVO,SN_BLOQUEADO,PASSWORD,FEC_CREACION,ID_ROL,ID_TIPO_DOC)
VALUES ('jherrera','Jose Reinel','Herrera Osorio','3115546230','calle 71 sur # 93 d 50 tekoa III bloque 3 casa 5 bosa recreo','joseherrera_094@hotmail.com','1012411225',-1,-1,'123',GETDATE(),1,1)
GO
SELECT* FROM USUARIO
GO
INSERT INTO CATEGORIA (ID_CATEG,NOMBRE_CATEG,SN_ACTIVO,USUARIO,FEC_CREACION)
VALUES (1,'ABARROTES',-1,'jherrera',GETDATE())

INSERT INTO CATEGORIA (ID_CATEG,NOMBRE_CATEG,SN_ACTIVO,USUARIO,FEC_CREACION)
VALUES (2,'FRUTAS',-1,'jherrera',GETDATE())

INSERT INTO CATEGORIA (ID_CATEG,NOMBRE_CATEG,SN_ACTIVO,USUARIO,FEC_CREACION)
VALUES (3,'VERDURAS',-1,'jherrera',GETDATE())

INSERT INTO CATEGORIA (ID_CATEG,NOMBRE_CATEG,SN_ACTIVO,USUARIO,FEC_CREACION)
VALUES (4,'LACTEOS',-1,'jherrera',GETDATE())
GO
SELECT * FROM CATEGORIA

INSERT INTO PRODUCTO (NOMBRE_PRODUC,SN_ACTIVO,USUARIO,URL_IMAGEN,CANTIDAD,PRECIO_UNI,FEC_CREACION,ID_CATEG)
VALUES ('MANZANA',-1,'jherrera','',5,1000,GETDATE(),2)
GO
SELECT * FROM PRODUCTO


