USE BD_Sistema_Ventas
GO
IF OBJECT_ID('CATEGORIA') IS NOT NULL
	DROP TABLE CATEGORIA
GO
CREATE TABLE CATEGORIA
(
	ID_CATEG		INT				NOT NULL PRIMARY KEY ,
	NOMBRE_CATEG	VARCHAR(50)		NOT NULL,
	SN_ACTIVO		INT				NOT NULL,
	USUARIO			VARCHAR(50)		NOT NULL,
	FEC_CREACION	SMALLDATETIME	NOT NULL
)
GO
CREATE INDEX IDX_CATEG ON CATEGORIA (NOMBRE_CATEG)
GO
