USE BD_Sistema_Ventas
GO

IF OBJECT_ID('PEDIDO') IS NOT NULL
	DROP TABLE PEDIDO
GO
CREATE TABLE PEDIDO
(
	ID_PEDIDO		INT				NOT NULL IDENTITY(1,1) PRIMARY KEY ,
	CANTIDAD		INT				NOT NULL,
	PRECIO_UNI		NUMERIC(18,2)	NOT NULL,
	DESCUENTO		NUMERIC(6,2)	NOT NULL,
	TOTAL_PEDIDO	NUMERIC(18,2)	NOT NULL,
	COD_ESTADO		INT				NOT NULL,
	FEC_PEDIDO		SMALLDATETIME	NOT NULL,
	ESTADO_PED		INT				NOT NULL, --1-EXITOSO,2-PENDIENTE
	USUARIO			VARCHAR(50)		NOT NULL,
	ID_PRODUCTO		INT				NOT NULL,
		
)
GO
CREATE INDEX IDX_PEDIDO ON PEDIDO (ID_PEDIDO)
GO
