USE BD_Sistema_Ventas
GO
IF OBJECT_ID('PRODUCTO') IS NOT NULL
	DROP TABLE PRODUCTO
GO
CREATE TABLE PRODUCTO
(
	ID_PRODUCTO		INT				NOT NULL IDENTITY(1,1) PRIMARY KEY ,
	NOMBRE_PRODUC	VARCHAR(50)		NOT NULL,
	SN_ACTIVO		INT				NOT NULL,
	USUARIO			VARCHAR(50)		NOT NULL,
	URL_IMAGEN		VARCHAR(2000)	NULL,
	CANTIDAD		INT				NOT NULL,
	PRECIO_UNI		NUMERIC(18,2)	NOT NULL,
	--DESCUENTO		NUMERIC(6,2)	NOT NULL,
	FEC_CREACION	SMALLDATETIME	NOT NULL,
	ID_CATEG		INT				NOT NULL
)
GO
CREATE INDEX IDX_PRODUCT ON PRODUCTO (NOMBRE_PRODUC)
GO
