USE BD_Sistema_Ventas
GO
IF OBJECT_ID('TIPO_DOCUMENTO') IS NOT NULL
	DROP TABLE TIPO_DOCUMENTO
GO
CREATE TABLE TIPO_DOCUMENTO
(
	ID_TIPO_DOC				INT				NOT NULL PRIMARY KEY ,
	NOMBRE_TIPO_DOC			VARCHAR(50)		NOT NULL,
	FEC_CREACION			SMALLDATETIME	NOT NULL
)
GO
CREATE INDEX IDX_TIPO_DOC ON TIPO_DOCUMENTO (NOMBRE_TIPO_DOC)
GO
