USE BD_Sistema_Ventas
GO
IF OBJECT_ID('USUARIO') IS NOT NULL
	DROP TABLE USUARIO
GO
CREATE TABLE USUARIO
(
	USUARIO			VARCHAR(50)	 PRIMARY KEY	NOT NULL,
	NOMBRE			VARCHAR(50)					NOT NULL,
	APELLIDO		VARCHAR(50)					NOT NULL,
	CELULAR			VARCHAR(10)					NOT NULL,
	DIRECCION		VARCHAR(200)				NOT NULL,
	EMAIL			VARCHAR(50)					NOT NULL,
	NRO_DOC			VARCHAR(10)					NOT NULL,
	SN_ACTIVO		INT							NOT NULL,
	SN_BLOQUEADO	INT							NOT NULL,
	PASSWORD		VARCHAR(50)					NOT NULL,
	FEC_CREACION	SMALLDATETIME				NOT NULL,
	ID_ROL			INT							NOT NULL,	
	ID_TIPO_DOC		INT							NOT NULL,	
	)
CREATE INDEX IDX_USUARIO ON USUARIO (USUARIO)
GO
CREATE INDEX IDX_LOGIN1 ON USUARIO (EMAIL,PASSWORD)
GO
CREATE INDEX IDX_LOGIN2 ON USUARIO (USUARIO,PASSWORD)
GO